[server]
port = 4433
host = "127.0.0.1"

[client]
port = 4434
host = "127.0.0.1"

[peers]
peers = [["BbUnoX5gsfg3MbkC1jbWLXuCnkprB1om9DaqPfYbhRu2", "127.0.0.1:4422", 10]]

[keys]
rsa_cert_path = "keys/rsa-cert.pem"
rsa_key_path = "keys/rsa-key.pem"
ed25519_key_path = "keys/iden.json"
